package constants

type BankCode string

const (
	BankCode_ABBANK                  BankCode = "ABBANK"
	BankCode_ACB                     BankCode = "ACB"
	BankCode_AGRIBANK                BankCode = "AGRIBANK"
	BankCode_BAC_A_BANK              BankCode = "BAC_A_BANK"
	BankCode_BAOVIET_BANK            BankCode = "BAOVIET_BANK"
	BankCode_BIDC                    BankCode = "BIDC"
	BankCode_BIDV                    BankCode = "BIDV"
	BankCode_CAKE                    BankCode = "CAKE"
	BankCode_CBBANK                  BankCode = "CBBANK"
	BankCode_CIMB                    BankCode = "CIMB"
	BankCode_COOP_BANK               BankCode = "COOP_BANK"
	BankCode_DBS_BANK                BankCode = "DBS_BANK"
	BankCode_DONG_A_BANK             BankCode = "DONG_A_BANK"
	BankCode_EXIMBANK                BankCode = "EXIMBANK"
	BankCode_GPBANK                  BankCode = "GPBANK"
	BankCode_HDBANK                  BankCode = "HDBANK"
	BankCode_HONGLEONG_BANK          BankCode = "HONGLEONG_BANK"
	BankCode_HSBC                    BankCode = "HSBC"
	BankCode_IBK_HCM                 BankCode = "IBK_HCM"
	BankCode_INDOVINA_BANK           BankCode = "INDOVINA_BANK"
	BankCode_KASIKORN_BANK           BankCode = "KASIKORN_BANK"
	BankCode_KIENLONG_BANK           BankCode = "KIENLONG_BANK"
	BankCode_KOOKMIN_BANK_HCM        BankCode = "KOOKMIN_BANK_HCM"
	BankCode_LIENVIETPOST_BANK       BankCode = "LIENVIETPOST_BANK"
	BankCode_LPBANK                  BankCode = "LPBANK"
	BankCode_LIOBANK                 BankCode = "LIOBANK"
	BankCode_MBBANK                  BankCode = "MBBANK"
	BankCode_MBV                     BankCode = "MBV"
	BankCode_MSB                     BankCode = "MSB"
	BankCode_NAM_A_BANK              BankCode = "NAM_A_BANK"
	BankCode_NCB                     BankCode = "NCB"
	BankCode_NONGHYUP_BANK_HN        BankCode = "NONGHYUP_BANK_HN"
	BankCode_OCB                     BankCode = "OCB"
	BankCode_OCEANBANK               BankCode = "OCEANBANK"
	BankCode_PGBANK                  BankCode = "PGBANK"
	BankCode_PUBLIC_BANK             BankCode = "PUBLIC_BANK"
	BankCode_PVCOM_BANK              BankCode = "PVCOM_BANK"
	BankCode_SACOMBANK               BankCode = "SACOMBANK"
	BankCode_SAIGONBANK              BankCode = "SAIGONBANK"
	BankCode_SCB                     BankCode = "SCB"
	BankCode_SEA_BANK                BankCode = "SEA_BANK"
	BankCode_SHB                     BankCode = "SHB"
	BankCode_SHINHAN_BANK            BankCode = "SHINHAN_BANK"
	BankCode_STANDARD_CHARTERED_BANK BankCode = "STANDARD_CHARTERED_BANK"
	BankCode_TECHCOMBANK             BankCode = "TECHCOMBANK"
	BankCode_TIMO                    BankCode = "TIMO"
	BankCode_TPBANK                  BankCode = "TPBANK"
	BankCode_UBANK                   BankCode = "UBANK"
	BankCode_UNITED_OVERSEAS_BANK    BankCode = "UNITED_OVERSEAS_BANK"
	BankCode_VIB                     BankCode = "VIB"
	BankCode_VIET_A_BANK             BankCode = "VIET_A_BANK"
	BankCode_VIET_BANK               BankCode = "VIET_BANK"
	BankCode_BANVIET                 BankCode = "BANVIET"
	BankCode_VIETCOMBANK             BankCode = "VIETCOMBANK"
	BankCode_VIETINBANK              BankCode = "VIETINBANK"
	BankCode_VIKKI                   BankCode = "VIKKI"
	BankCode_VPBANK                  BankCode = "VPBANK"
	BankCode_VRB                     BankCode = "VRB"
	BankCode_WOORI_BANK              BankCode = "WOORI_BANK"
)
