package constants

type BankKey string

const (
	BankKey_ABBANK                  BankKey = "abbank"
	BankKey_ACB                     BankKey = "acb"
	BankKey_AGRIBANK                BankKey = "agribank"
	BankKey_BAC_A_BANK              BankKey = "bacabank"
	BankKey_BAOVIET_BANK            BankKey = "baoviet"
	BankKey_BANVIET                 BankKey = "banviet"
	BankKey_BIDC                    BankKey = "bidc"
	BankKey_BIDV                    BankKey = "bidv"
	BankKey_CAKE                    BankKey = "cake"
	BankKey_CBBANK                  BankKey = "cbbank"
	BankKey_CIMB                    BankKey = "cimb"
	BankKey_COOP_BANK               BankKey = "coopbank"
	BankKey_DBS_BANK                BankKey = "dbsbank"
	BankKey_DONG_A_BANK             BankKey = "dongabank" /** @deprecated - Chuyển giao cho HDBank, đổi tên thành Vikki Digital Bank */
	BankKey_EXIMBANK                BankKey = "eximbank"
	BankKey_GPBANK                  BankKey = "gpbank"
	BankKey_HDBANK                  BankKey = "hdbank"
	BankKey_HONGLEONG_BANK          BankKey = "hongleongbank"
	BankKey_HSBC                    BankKey = "hsbc"
	BankKey_IBK_HCM                 BankKey = "ibkhcm"
	BankKey_IBK_HN                  BankKey = "ibkhn"
	BankKey_INDOVINA_BANK           BankKey = "indovinabank"
	BankKey_KASIKORN_BANK           BankKey = "kasikorn"
	BankKey_KIENLONG_BANK           BankKey = "kienlongbank"
	BankKey_KOOKMIN_BANK_HCM        BankKey = "kookminhcm"
	BankKey_KOOKMIN_BANK_HN         BankKey = "kookminhn"
	BankKey_LIENVIETPOST_BANK       BankKey = "lienvietpostbank" /** @deprecated Đổi tên thành Lộc Phát Việt Nam (LPBANK) */
	BankKey_LPBANK                  BankKey = "lpbank"
	BankKey_LIOBANK                 BankKey = "liobank"
	BankKey_MBBANK                  BankKey = "mbbank"
	BankKey_MBV                     BankKey = "mbv"
	BankKey_MSB                     BankKey = "msb"
	BankKey_NAM_A_BANK              BankKey = "namabank"
	BankKey_NCB                     BankKey = "ncb"
	BankKey_NONGHYUP_BANK_HN        BankKey = "nonghyup"
	BankKey_OCB                     BankKey = "ocb"
	BankKey_OCEANBANK               BankKey = "oceanbank" /** @deprecated Chuyển giao cho MBBank đổi tên thành MBV */
	BankKey_PGBANK                  BankKey = "pgbank"
	BankKey_PUBLIC_BANK             BankKey = "publicbank"
	BankKey_PVCOM_BANK              BankKey = "pvcombank"
	BankKey_SACOMBANK               BankKey = "sacombank"
	BankKey_SAIGONBANK              BankKey = "saigonbank"
	BankKey_SCB                     BankKey = "scb"
	BankKey_SEA_BANK                BankKey = "seabank"
	BankKey_SHB                     BankKey = "shb"
	BankKey_SHINHAN_BANK            BankKey = "shinhanbank"
	BankKey_STANDARD_CHARTERED_BANK BankKey = "standardcharteredbank"
	BankKey_TECHCOMBANK             BankKey = "techcombank"
	BankKey_TIMO                    BankKey = "timo"
	BankKey_TPBANK                  BankKey = "tpbank"
	BankKey_UBANK                   BankKey = "ubank"
	BankKey_UNITED_OVERSEAS_BANK    BankKey = "uob"
	BankKey_VIB                     BankKey = "vib"
	BankKey_VIET_A_BANK             BankKey = "vietabank"
	BankKey_VIET_BANK               BankKey = "vietbank"
	BankKey_VIETCOMBANK             BankKey = "vietcombank"
	BankKey_VIETINBANK              BankKey = "vietinbank"
	BankKey_VIKKI                   BankKey = "vikki"
	BankKey_VPBANK                  BankKey = "vpbank"
	BankKey_VRB                     BankKey = "vrb"
	BankKey_WOORI_BANK              BankKey = "wooribank"
)
